// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIpWNP9j1jwot4OsLqJVOycyXkVCmxeos',
    appId: '1:338156506675:web:6394af38c53b408fd65d46',
    messagingSenderId: '338156506675',
    projectId: 'zoom-my-life',
    authDomain: 'zoom-my-life.firebaseapp.com',
    storageBucket: 'zoom-my-life.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE10_dUYUlb_-r5cRfpYuzQ-7u755beMw',
    appId: '1:338156506675:android:8c21cb7ff02823bbd65d46',
    messagingSenderId: '338156506675',
    projectId: 'zoom-my-life',
    storageBucket: 'zoom-my-life.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsL2fe--m3LaUy6_iDopM7-OOJQVazees',
    appId: '1:338156506675:ios:763cd20301c5d206d65d46',
    messagingSenderId: '338156506675',
    projectId: 'zoom-my-life',
    storageBucket: 'zoom-my-life.appspot.com',
    iosBundleId: 'com.zoommylife.zoomMyLifeApp',
  );
}
